// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ogl-exemptions/GridLayout.tsx": () => import("../components/mockups/ogl-exemptions/GridLayout.tsx")
};
